// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh66FN-7u5L5ChGBvFCTLI5kSHlPJ_2xI',
    appId: '1:239099708536:web:b0ebabe076c41903ea198d',
    messagingSenderId: '239099708536',
    projectId: 'co-lab-5gsij5',
    authDomain: 'co-lab-5gsij5.firebaseapp.com',
    storageBucket: 'co-lab-5gsij5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACUuQ85aKRvpiiakqUYg_u8S4iCGpFcYY',
    appId: '1:239099708536:android:7ab9f0d465686bceea198d',
    messagingSenderId: '239099708536',
    projectId: 'co-lab-5gsij5',
    storageBucket: 'co-lab-5gsij5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnJzRqg4I6cOR0mzPpEufxwc5wtg7rGj4',
    appId: '1:239099708536:ios:6b1617566926687bea198d',
    messagingSenderId: '239099708536',
    projectId: 'co-lab-5gsij5',
    storageBucket: 'co-lab-5gsij5.firebasestorage.app',
    androidClientId: '239099708536-6folg17u4ev1vq7aljodt4ick1h8qajk.apps.googleusercontent.com',
    iosClientId: '239099708536-hk3fm9u5rspp82qtkfds3moode4e4c8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.coLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnJzRqg4I6cOR0mzPpEufxwc5wtg7rGj4',
    appId: '1:239099708536:ios:6b1617566926687bea198d',
    messagingSenderId: '239099708536',
    projectId: 'co-lab-5gsij5',
    storageBucket: 'co-lab-5gsij5.firebasestorage.app',
    androidClientId: '239099708536-6folg17u4ev1vq7aljodt4ick1h8qajk.apps.googleusercontent.com',
    iosClientId: '239099708536-hk3fm9u5rspp82qtkfds3moode4e4c8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.coLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQwHX1OzLWfDGP-KKsJszHKQmgrOSlDPw',
    appId: '1:239099708536:web:671641c0b42b0e93ea198d',
    messagingSenderId: '239099708536',
    projectId: 'co-lab-5gsij5',
    authDomain: 'co-lab-5gsij5.firebaseapp.com',
    storageBucket: 'co-lab-5gsij5.firebasestorage.app',
  );
}
